sudo: required
language: generic
services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export IMG=$DOCKER_USERNAME/haskell-vim-now:$(git rev-parse --short HEAD)
  - docker build -t $IMG .
  - docker push $IMG

